---
- hosts: webserver
  remote_user: test1000
  become: yes
  tasks:
     - name: Installing webserver httpd
       yum: name=httpd state=installed
       tags: insatll
     - name: Copy index.htm 
       copy: src=index.html dest=/var/www/html
       tags: insatll
     - name: starting httpd
       service: name=httpd state=started
       tags: service
